board:
  title: "Monthly Budget Board"
google_sheets:
  sheet_name: "Active Budget"
columns:
  - id: "backlog"
    title: "Backlog"
    cash_in_play: 0
  - id: "rollover"
    title: "Rollover"
    cash_in_play: 500
  - id: "in_budget"
    title: "In Month's Budget"
    cash_in_play: 4500
  - id: "unfunded"
    title: "Unfunded"
    cash_in_play: 0
