board:
  title: "Monthly Budget Board"
google_sheets:
  sheet_name: "Active Budget"
  envelopes_sheet_name: "Envelopes"
columns:
  - id: "backlog"
    title: "Backlog"
  - id: "rollover"
    title: "Rollover"
  - id: "in_budget"
    title: "In Month's Budget"
  - id: "unfunded"
    title: "Unfunded"

